/* Automatically generated by scripts/build_docs.py. Do not edit manually. */
const DOC_REGISTRY = [
  {
    "section": "架构与设计",
    "items": [
      {
        "id": "DOC-00",
        "path": "doc/architecture/DOC-00-解决方案概述.md",
        "title": "DOC-00 解决方案概述",
        "desc": "项目原始方案：价值定位、核心场景、实施路径",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-01",
        "path": "doc/architecture/DOC-01-系统架构规格书.md",
        "title": "DOC-01 系统架构规格书",
        "desc": "四层架构、组件交互、数据流、ADR 决策记录",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-02",
        "path": "doc/architecture/DOC-02-模块分解设计.md",
        "title": "DOC-02 模块分解设计",
        "desc": "11 个模块职责边界、接口契约、依赖关系",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-03",
        "path": "doc/architecture/DOC-03-AI-LLM集成设计.md",
        "title": "DOC-03 AI/LLM 集成设计",
        "desc": "模型选型、RAG 流水线、Prompt 工程、降级策略",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-04",
        "path": "doc/architecture/DOC-04-安全架构文档.md",
        "title": "DOC-04 安全架构文档",
        "desc": "JWT+RBAC 认证、AES-256-GCM 加密、审计日志",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-17",
        "path": "doc/architecture/DOC-17-技术栈全景方案.md",
        "title": "DOC-17 技术栈全景方案",
        "desc": "10 层技术栈完整说明与选型对比",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-25",
        "path": "doc/architecture/DOC-25-终端Agent设计方案.md",
        "title": "DOC-25 终端 Agent 设计方案",
        "desc": "Agent 技术选型、采集指标、远程执行、健康评估",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-27",
        "path": "doc/architecture/DOC-27-术语表与缩写.md",
        "title": "DOC-27 术语表与缩写",
        "desc": "全项目术语、缩写和定义速查",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-28",
        "path": "doc/architecture/DOC-28-ADR决策记录.md",
        "title": "DOC-28 ADR 决策记录",
        "desc": "关键架构决策记录（ADR）日志",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-30",
        "path": "doc/architecture/DOC-30-网络拓扑发现与分析设计.md",
        "title": "DOC-30 网络拓扑发现与分析设计",
        "desc": "SNMP、LLDP拓扑自动发现算法与物理连线推导",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-31",
        "path": "doc/architecture/DOC-31-软件许可审计与合规设计.md",
        "title": "DOC-31 软件许可审计与合规设计",
        "desc": "注册表客户端审计、许可分配计算及超额卸载流程",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-32",
        "path": "doc/architecture/DOC-32-自动化脚本库与安全策略.md",
        "title": "DOC-32 自动化脚本库与安全策略",
        "desc": "内置脚本规格、参数Schema校验、沙箱安全防护与审批流",
        "status": "初稿",
        "badge": "blue"
      }
    ]
  },
  {
    "section": "API 与通信",
    "items": [
      {
        "id": "DOC-05",
        "path": "doc/api/DOC-05-REST-API规范.md",
        "title": "DOC-05 REST API 规范",
        "desc": "13 个模块完整 API 端点、请求/响应示例、错误码",
        "status": "初稿",
        "badge": "green"
      },
      {
        "id": "DOC-06",
        "path": "doc/api/DOC-06-Webhook与回调规范.md",
        "title": "DOC-06 Webhook 与回调",
        "desc": "钉钉/企微消息格式、事件总线、重试幂等策略",
        "status": "初稿",
        "badge": "green"
      },
      {
        "id": "DOC-07",
        "path": "doc/api/DOC-07-Agent服务器通信协议.md",
        "title": "DOC-07 Agent 通信协议",
        "desc": "Zabbix Agent 2 + 自研 Agent 协议（WebSocket/mTLS）",
        "status": "初稿",
        "badge": "green"
      },
      {
        "id": "DOC-24",
        "path": "doc/api/DOC-24-钉钉集成详细设计.md",
        "title": "DOC-24 钉钉集成详细设计",
        "desc": "钉钉 Stream Mode、消息卡片、审批流、用户同步",
        "status": "初稿",
        "badge": "green"
      }
    ]
  },
  {
    "section": "数据设计",
    "items": [
      {
        "id": "DOC-08",
        "path": "doc/data/DOC-08-数据模型规格书.md",
        "title": "DOC-08 数据模型规格书",
        "desc": "23 个实体完整 DDL、ER 图、索引与分区策略",
        "status": "初稿",
        "badge": "orange"
      },
      {
        "id": "DOC-09",
        "path": "doc/data/DOC-09-数据字典.md",
        "title": "DOC-09 数据字典",
        "desc": "全部字段类型、约束、业务含义、有效值",
        "status": "初稿",
        "badge": "orange"
      },
      {
        "id": "DOC-10",
        "path": "doc/data/DOC-10-数据保留与归档策略.md",
        "title": "DOC-10 数据保留与归档策略",
        "desc": "热/温/冷分层、下采样、GDPR 合规",
        "status": "初稿",
        "badge": "orange"
      }
    ]
  },
  {
    "section": "部署与运维",
    "items": [
      {
        "id": "DOC-11",
        "path": "doc/deployment/DOC-11-部署指南.md",
        "title": "DOC-11 部署指南",
        "desc": "Docker Compose 部署、GPU 配置、初始化引导",
        "status": "初稿",
        "badge": "purple"
      },
      {
        "id": "DOC-12",
        "path": "doc/deployment/DOC-12-运维手册.md",
        "title": "DOC-12 运维手册",
        "desc": "备份恢复、服务管理、监控告警、故障排查",
        "status": "初稿",
        "badge": "purple"
      },
      {
        "id": "DOC-13",
        "path": "doc/deployment/DOC-13-LLM运维指南.md",
        "title": "DOC-13 LLM 运维指南",
        "desc": "百炼 DeepSeek-V4、私有化模型网关、向量模型与 fallback 运维",
        "status": "初稿",
        "badge": "purple"
      },
      {
        "id": "DOC-14",
        "path": "doc/deployment/DOC-14-灾难恢复计划.md",
        "title": "DOC-14 灾难恢复计划",
        "desc": "L1-L4 灾难分级、数据恢复、全量重建",
        "status": "初稿",
        "badge": "purple"
      },
      {
        "id": "DOC-26",
        "path": "doc/deployment/DOC-26-大型园区部署架构.md",
        "title": "DOC-26 大型园区部署架构",
        "desc": "2000-5000 台规模、多 VLAN Proxy、分布式部署、容量规划",
        "status": "初稿",
        "badge": "purple"
      }
    ]
  },
  {
    "section": "用户指南",
    "items": [
      {
        "id": "DOC-15",
        "path": "doc/user-guides/DOC-15-管理员指南.md",
        "title": "DOC-15 管理员指南",
        "desc": "控制台操作、资产管理、用户管理、报表",
        "status": "初稿",
        "badge": "cyan"
      },
      {
        "id": "DOC-16",
        "path": "doc/user-guides/DOC-16-终端用户指南.md",
        "title": "DOC-16 终端用户指南",
        "desc": "钉钉/企微自助服务、常用命令、截图提交",
        "status": "初稿",
        "badge": "cyan"
      },
      {
        "id": "DOC-29",
        "path": "doc/user-guides/DOC-29-常见问题排查.md",
        "title": "DOC-29 常见问题排查",
        "desc": "终端用户 & 管理员常见问题与解决方案",
        "status": "初稿",
        "badge": "cyan"
      }
    ]
  },
  {
    "section": "开发与测试",
    "items": [
      {
        "id": "DOC-18",
        "path": "doc/development/DOC-18-开发者环境搭建指南.md",
        "title": "DOC-18 开发者环境搭建",
        "desc": "本地环境、项目结构、VS Code 调试、Git 工作流",
        "status": "初稿",
        "badge": "red"
      },
      {
        "id": "DOC-19",
        "path": "doc/development/DOC-19-编码规范.md",
        "title": "DOC-19 编码规范",
        "desc": "Python/TypeScript 规范、Commit 规范、CR 清单",
        "status": "初稿",
        "badge": "red"
      },
      {
        "id": "DOC-20",
        "path": "doc/development/DOC-20-贡献指南.md",
        "title": "DOC-20 贡献指南",
        "desc": "分支策略、PR 流程、Issue 模板、模块开发指南",
        "status": "初稿",
        "badge": "red"
      },
      {
        "id": "DOC-21",
        "path": "doc/testing/DOC-21-测试策略.md",
        "title": "DOC-21 测试策略",
        "desc": "测试金字塔、LLM 评估、性能基准、安全测试",
        "status": "初稿",
        "badge": "red"
      }
    ]
  },
  {
    "section": "功能与页面设计",
    "items": [
      {
        "id": "DOC-22",
        "path": "doc/DOC-22-功能设计文档.md",
        "title": "DOC-22 功能设计文档",
        "desc": "12 个功能模块全景、优先级矩阵、功能交互流程",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-23",
        "path": "doc/DOC-23-页面设计文档.md",
        "title": "DOC-23 页面设计文档",
        "desc": "设计系统、3 页面/12 子页面布局、组件与交互规范",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-33",
        "path": "doc/DOC-33-资产成本与盘活设计.md",
        "title": "DOC-33 资产成本与盘活设计",
        "desc": "资产成本、折旧残值、IP/MAC、闲置盘活、自动盘点与预算建议",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-34",
        "path": "doc/DOC-34-报表分析与AI报表生成设计.md",
        "title": "DOC-34 报表分析与 AI 报表生成设计",
        "desc": "报表体系、页面结构、指标口径、AI 生成条件与审批边界",
        "status": "初稿",
        "badge": "blue"
      },
      {
        "id": "DOC-35",
        "path": "doc/DOC-35-AI资产管家与企业AI网关设计.md",
        "title": "DOC-35 AI资产管家与企业AI网关设计",
        "desc": "企业内部 AI API 中转、统一 Key、模型资产、用量成本与审计治理",
        "status": "初稿",
        "badge": "blue"
      }
    ]
  }
];

const DOCS_STATS = {
  count: 36,
  categories: 7,
  size_kb: 566,
  version: 'v1.0'
};
